In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])

In [3]:
arr

array([1, 2, 3])

In [4]:
m = [[1,2,3],[3,4,5],[6,7,8]]
m

[[1, 2, 3], [3, 4, 5], [6, 7, 8]]

In [5]:
n = np.array(m)
n

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 10, 45)

array([0])

In [8]:
np.arange(0, 10), 4

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 4)

In [9]:
np.zeros(0)

array([], dtype=float64)

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand(1,20)

array([[0.25881772, 0.21788711, 0.088119  , 0.52729345, 0.22938586,
        0.98389567, 0.08352988, 0.92732227, 0.1004618 , 0.72632172,
        0.46847182, 0.17020136, 0.94733842, 0.96887836, 0.69461093,
        0.83697253, 0.21858469, 0.03983264, 0.994108  , 0.9889793 ]])

In [15]:
np.random.randn(2)

array([-0.64377734, -0.34753392])

In [16]:
np.random.randint(5, 20, 12)

array([11,  6, 19, 13,  6,  9,  6,  7, 16, 16, 16,  8])

In [17]:
arr = np.arange(25)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [21]:
arr.max

<function ndarray.max>

arr.max()

In [24]:
print("ehlloe")

ehlloe


In [28]:
x = np.arange(5,50)

In [30]:
x

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [32]:
x.max()

49

In [34]:
x.min()

5

In [36]:
x.argmax()

44

In [38]:
x.argmin()

0

In [42]:
x.shape

(45,)

In [44]:
x.reshape(5,5)

ValueError: cannot reshape array of size 45 into shape (5,5)

In [46]:
arr.dtype

dtype('int32')

In [48]:
x.dtype

dtype('int32')

In [50]:
a = np.arange(0,11)

In [52]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
a + a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [56]:
a - a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [60]:
a + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [62]:
1/1

1.0

1

In [65]:
1/0

ZeroDivisionError: division by zero

In [67]:
0/0

ZeroDivisionError: division by zero

###  Excercises